# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 036aa93418eedfb27f32ab1d2343460a85d1d4b9

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: localhost
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false
    from: pos@localhost

authentication:
    oauth:
        clientid: posapp
        secret: mySecretOAuthSecret
        # Token is valid 1 day
        tokenValidityInSeconds: 86400

swagger:
    title: pos API
    description: pos applications and beyond!
    version: 0.0.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
